#!/bin/sh
case $1 in
"-checkout")
    echo '\nこんにちは!\n
        今回はプロジェクト演習で使用するsvnの基本的な使い方をマスターしましょう!\n
        Enterを押して次に進んでください!\n'
    read -p ""
    echo "まずは自分のところで作業できるようにリポジトリからディレクトリを取得しましょう!\n
        取得のためにはcheckoutコマンドを使います!\n
        svn checkout http://bluetree.kyoto-su.ac.jp/repositories/PP/G4\n
        ターミナルを別で開いて実行完了したらEnterを押してください!\n"
    read -p ""
    if [ -d "G4" ]; then
        echo "リポジトリからディレクトリを取得しました！\n
            これでリポジトリからディレクトリを取得できるようになりました！
            次にcommitを体験してみましょう!\n
            test-command -commit \n
            を実行してください!"
    else
        echo "リポジトリからディレクトリを取得できませんでした！\n
            エラーが発生している可能性があります！\n
            もう一度やり直してください！"
        exit 1
    fi
    ;;
"-commit")
    echo "ここではcommitの体験をします。\n
          commitとは、作業の変更をリモートリポジトリに保存することです。\n
          作業の変更を行う前に別ターミナルを開きG4ディレクトリに移動し以下のコマンドを実行しましょう!\n
            svn update\n
          これでリポジトリの最新版を取得できます。\n
          "
    read -p ""
    echo "次にG4ディレクトリ内にファイルを作成しましょう。\n
          作成するファイル名は「test.txt」とします。\n"
    read -p ""
    echo "作業が完了したら以下のコマンドを実行してください。\n
            svn commit -m 'test commit'\n
            このtest commitはコミットメッセージです。実際には作業した内容など適宜変更してください!\n"
    read -p ""
    echo "これでcommitが完了しました!\n
          他のメンバーが作業を行った場合は、先ほどのupdateコマンドを実行して最新版を取得しましょう!\n"
    read -p ""
    echo "ではupdateで追加したファイルがあることを確認しましょう!\n
        一度先ほど作成したtext.txtを削除した後に以下のコマンドを実行してください!\n
          svn update\n"
    read -p ""
    if [ -f "G4/test.txt" ]; then
        echo "無事updateにより先ほど削除したtest.txtが取得されました!"
    else
        echo "updateにエラーが発生しました!\n
            エラーが発生している可能性があります！\n
            もう一度やり直してください！"
        exit 1
    fi
    read -p ""
    echo "最後にリモートリポジトリからtest.txtを削除しましょう!\n
          以下のコマンドを実行してください!\n
            svn delete test.txt\n
          これでリモートリポジトリからtest.txtが削除されました!\n
          これでcommitの体験は終了です!\n
          お疲れ様でした!\n"

    ;;

"-help")
    echo "-commit: commitの体験をします。\n
          -checkout: checkoutの体験をします。\n
          https://subversion.apache.org/docs/ を参考にしてください！\n"
    ;;
*)
    echo "無効なオプションです。"
    exit 1
    ;;
esac
